
@baseURL = http://localhost:3000

# GetHelloWord
###
# @name GetHelloWord
Get {{baseURL}}/home/hello

# Get users
###
# @name GetUsers
Get {{baseURL}}/users

# Get user by id
###
# @name GetUserById
Get {{baseURL}}/users/1

# Create user
###
Post {{baseURL}}/users/create
Content-Type: application/json
{
  "name": "John Doe",
  "email": "25",
  "password": "123456",
  "role": "admin",
  "phoneNumber": "1234567890",
  "isActive": true
}